// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbIgM7E7LdtepTwxgHbE0D1JvHq9h35tI',
    appId: '1:852124663142:web:b9a1eae8126814ef781ca7',
    messagingSenderId: '852124663142',
    projectId: 'kanade-60135',
    authDomain: 'kanade-60135.firebaseapp.com',
    storageBucket: 'kanade-60135.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD99FlzME01R6bbEpwQXja90YkhD1Nx5N4',
    appId: '1:852124663142:android:060d9f180b20c65f781ca7',
    messagingSenderId: '852124663142',
    projectId: 'kanade-60135',
    storageBucket: 'kanade-60135.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtahuN2DtyM7RXOswDDloRPlWJJBL378I',
    appId: '1:852124663142:ios:c6b259ac3294f537781ca7',
    messagingSenderId: '852124663142',
    projectId: 'kanade-60135',
    storageBucket: 'kanade-60135.firebasestorage.app',
    iosBundleId: 'com.spiralnuggets.kanade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtahuN2DtyM7RXOswDDloRPlWJJBL378I',
    appId: '1:852124663142:ios:a8dd4aa91a3a4c2f781ca7',
    messagingSenderId: '852124663142',
    projectId: 'kanade-60135',
    storageBucket: 'kanade-60135.firebasestorage.app',
    iosBundleId: 'com.spiralnuggets.kanade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbIgM7E7LdtepTwxgHbE0D1JvHq9h35tI',
    appId: '1:852124663142:web:0a22d22430e74bc5781ca7',
    messagingSenderId: '852124663142',
    projectId: 'kanade-60135',
    authDomain: 'kanade-60135.firebaseapp.com',
    storageBucket: 'kanade-60135.firebasestorage.app',
  );
}
